[package]
name = "candle-holder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
candle-core = { version = "0.4.1", features = ["metal"] }
candle-nn = "0.4.1"
dyn-fmt = "0.4.0"
hf-hub = "0.3.2"
lazy_static = "1.4.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokenizers = { version = "0.19.1", features = ["http"] }
