[package]
name = "candle-holder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
candle-core = "0.3.1"
candle-nn = "0.3.1"
candle-transformers = "0.3.1"
hf-hub = "0.3.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokenizers = "0.15.0"
